### ISSUE TITLE
Module 13 Machine learning 9.3 uses Azure CLI instead

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20774_Perform-Cloud-Data-Science-with-Azure-Machine-Learning#12]
The latest version of the Machine Learning Data Science VM uses Machine Learning Server 9.3. The Administration Utility is replaced by the CLI.
To configure the VM you can use **az ml admin bootstrap,** so the instructions of Module 13 Exercise 2 task 3 have to be updated. 

https://docs.microsoft.com/en-us/machine-learning-server/operationalize/configure-admin-cli-launch
The tool you use to set up and manage your configuration depends on your version:

In Machine Learning Server 9.3, use the command line interface (CLI).
In versions 9.0 - 9.2, use the Administration Utility.

**Comment by JohnPWSharp** [comment]
The lab and LAK have been updated.
