### ISSUE TITLE
Module 05, Exercise 02, Task 02, Step 08 

### ISSUE THREAD

**Issue by mreherefortea** [MicrosoftLearning/20774_Perform-Cloud-Data-Science-with-Azure-Machine-Learning#13]
AK is missing the data after type.  It reads as follows:
8. In both Comma separated list boxes, type:

but is missing the following listing: 

CustomerName, TransactionAmount, OutstandingBalance, TaxAmount, TransactionDate,
Season, Holiday, Promo, PKIDDate. 

Thank you!

**Comment by JohnPWSharp** [comment]
LAK updated
