### ISSUE TITLE
Where are the lab files and demo files?

### ISSUE THREAD

**Issue by pdlab** [MicrosoftLearning/20774_Perform-Cloud-Data-Science-with-Azure-Machine-Learning#19]
Does this have any updated lab files and demo files? I don't see them in this repository.
Where are the converted word docs for the lab instructions?

There is a note in the allfiles folder indicating going somewhere that doesn't exist.

Thanks.

**Comment by JohnPWSharp** [comment]
Click on the home page for the 20774 repo, and then click Releases. Alternatively, go to https://github.com/MicrosoftLearning/20774_Perform-Cloud-Data-Science-with-Azure-Machine-Learning/releases
